#include <Arduino.h>
#include <TFT_eSPI.h>
#include <lvgl.h>
#include "theme.h"
#include "header.h"
#include "screens.h"
#include "screen_enroll.h"
#include "screen_browse.h"
#include "screen_menu.h"
#include "screen_pos.h"
#include "screen_blocked.h"
#include "screen_screensaver.h"
#include "screen_splash.h"
#include "screen_sd_error.h"
#include "screen_setup_wizard.h"
#include "screen_payment_edit.h"
#include "screen_item_edit.h"
#include "screen_restock.h"
#include "screen_add_item.h"
#include "screen_add_user.h"
#include "screen_gm65_test.h"
#include "screen_gm65_settings.h"
#include "screen_extras.h"
#include "screen_admin_login.h"
#include "idle_timer.h"
#include "session_timer.h"
#include "system_alerts.h"
#include "rtc.h"
#include "ui.h"
#include "users.h"
#include "items.h"
#include "buttons.h"
#include "backlight.h"
#include "db.h"
#include "boot_log.h"
#include "clock_health.h"
#include <SD.h>
#include "webserver.h"
#include "screen_webportal.h"

/*
  Author--- LogicishDesigns
  Date----- September 2026
  Function- Entry point: hardware bring-up (display/LVGL/backlight/DB/scanner/WiFi),
            the IDLE ("Start") screen, badge-scan routing to whichever screen wants
            it, and the main setup()/loop() Arduino pair.
  Notes---- Every top-level "which screen owns this scan" decision funnels through
            on_scan() below; individual screens expose their own *_on_scan()
            interceptor so this file never needs to know their internal state.
*/

// ── hardware ──────────────────────────────────────────────────────────────────
TFT_eSPI       tft;
HardwareSerial scanner(1);

// 2026-08-26 — a soft ESP32 reset (e.g. a firmware reflash) doesn't necessarily power-
// cycle the GM65 (confirmed ambiguous earlier — see project memory), so it can come back
// up still holding whatever live/RAM state it had *before* the reset — caught for real
// when a reflash landed while the screensaver had it in Manual/scan-off mode, and it
// stayed off after boot with nothing to notice or correct it. Force the known-good
// locked config on every boot rather than trusting whatever state carried over. RAM-only
// writes (no EEPROM save — this isn't re-provisioning, just re-asserting), matching
// screen_gm65_test.cpp's act_setup_defaults() values exactly (see project memory:
// project_gm65_settings_lockin) but duplicated here rather than shared, per this
// codebase's established per-file self-contained convention for GM65 command helpers.
static void gm65_write_reg(uint8_t addr_hi, uint8_t addr_lo, uint8_t data) {
    const uint8_t cmd[9] = {0x7E, 0x00, 0x08, 0x01, addr_hi, addr_lo, data, 0xAB, 0xCD};
    scanner.write(cmd, 9);
}

// Boot scanner check, 2026-10-02: did the GM65 answer the boot writes at all, and do its
// registers read back as the locked config? Reads 0x0000-0x000D in one frame -- same
// command and reply layout as screen_gm65_settings.cpp (4-byte header {0x02 0x00 Types Lens},
// then the data, then 2 CRC bytes; the data does NOT start at offset 0). Also reports
// the setup-code lock (reg 0x0003 = 0x03, see screen_gm65_test.cpp) so a cart that ships
// with it off says so. Results go to the boot log and the Admin Menu alert banner.
// Slide Free board files, 2026-10-02 -- the game plays however many tierN.txt files it finds
// (stopping at the first gap), so a missing or empty one silently shrinks it rather than
// erroring. The cart ships with 5 (generated by tools/tilt_lab.py, copies in tools/slidefree/).
#define SLIDE_FREE_TIERS 5
static void boot_check_slide_free() {
    char missing[48] = "";
    for (int t = 1; t <= SLIDE_FREE_TIERS; t++) {
        char path[32];
        snprintf(path, sizeof(path), "/slidefree/tier%d.txt", t);
        File f = SD.open(path, FILE_READ);
        bool ok = f && f.size() > 0;
        if (f) f.close();
        if (ok) continue;
        size_t len = strlen(missing);
        snprintf(missing + len, sizeof(missing) - len, "%stier%d", len ? "+" : "", t);
    }
    if (missing[0]) {
        boot_log_note("slide_free_missing", "%s", missing);
        system_alerts_add_boot_issue("SLIDE FREE BOARD FILES MISSING");
    } else {
        boot_log_note("slide_free", "ok");
    }
}

#define GM65_READ_COUNT 0x0E
// Sends the 14-register read and collects whatever comes back until the bus goes quiet.
static size_t gm65_read_regs_raw(uint8_t *buf, size_t cap) {
    const uint8_t cmd[9] = {0x7E, 0x00, 0x07, 0x01, 0x00, 0x00, GM65_READ_COUNT, 0xAB, 0xCD};
    scanner.write(cmd, 9);

    size_t n = 0;
    uint32_t start = millis(), last_rx = 0;
    while (millis() - start < 500) {            // fault-guard if the module never answers
        if (scanner.available()) {
            while (scanner.available()) {
                int b = scanner.read();
                if (n < cap) buf[n++] = (uint8_t)b;
            }
            last_rx = millis();
        } else if (n > 0 && millis() - last_rx >= 40) {
            break;                              // reply received, bus quiet since
        }
        delay(1);
    }
    return n;
}

static void boot_check_scanner(bool acked) {
    uint8_t buf[64];
    size_t n = 0;
    const uint8_t *regs = nullptr;

    // Two tries. On the first boot after a reflash (2026-10-02, real hardware) the module
    // answers slower: one boot-write ACK (02 00 00 01 00 33 31) landed in the read window
    // and the read reply never showed. A second ask, after the line is quiet, gets it.
    for (int attempt = 0; attempt < 2 && !regs; attempt++) {
        if (attempt > 0) {
            delay(100);
            while (scanner.available()) scanner.read();
        }
        n = gm65_read_regs_raw(buf, sizeof(buf));

        // Prefer a frame whose Lens byte matches the count asked for; failing that, take any
        // {0x02 0x00} frame with room for all 14 registers that isn't a 7-byte write ACK
        // (02 00 00 01 00 33 31 -- Lens 0x01).
        for (int pass = 0; pass < 2 && !regs; pass++) {
            for (size_t i = 0; i + 4 + GM65_READ_COUNT <= n; i++) {
                if (buf[i] != 0x02 || buf[i + 1] != 0x00) continue;
                bool lens_ok = pass == 0 ? buf[i + 3] == GM65_READ_COUNT : buf[i + 3] != 0x01;
                if (lens_ok) { regs = buf + i + 4; break; }
            }
        }
        if (!regs && attempt == 0) Serial.println("[SCAN] boot readback missed -- asking once more");
    }

    if (!regs) {
        // Keep what did arrive, so the boot log shows the real reply to fix the parser from.
        char raw[3 * 24 + 8];
        int len = snprintf(raw, sizeof(raw), "%u:", (unsigned)n);
        for (size_t i = 0; i < n && i < 24 && len < (int)sizeof(raw) - 3; i++) {
            len += snprintf(raw + len, sizeof(raw) - len, "%02X", buf[i]);
        }
        boot_log_note("scanner_raw", "%s", raw);
        boot_log_note("scanner", "%s", acked ? "no_readback" : "NOT_RESPONDING");
        if (!acked) system_alerts_add_boot_issue("SCANNER NOT RESPONDING");
        else        system_alerts_add_boot_issue("SCANNER SETTINGS UNREADABLE");
        return;
    }

    bool settings_ok = regs[0x00] == 0x57 && regs[0x07] == 0x00 && regs[0x0A] == 0x64;
    bool qr_locked   = regs[0x03] == 0x03;
    boot_log_note("scanner", "%s", settings_ok ? "ok" : "SETTINGS_MISMATCH");
    boot_log_note("scanner_regs", "%02X/%02X/%02X", regs[0x00], regs[0x07], regs[0x0A]);
    boot_log_note("qr_config_lock", "%s", qr_locked ? "on" : "OFF");
    if (!settings_ok) system_alerts_add_boot_issue("SCANNER SETTINGS DIDN'T STICK");
    if (!qr_locked)   system_alerts_add_boot_issue("SCANNER SETUP-CODE LOCK IS OFF");
}

// Extra splash time once boot is finished, on top of however long boot itself took.
#define SPLASH_BONUS_MS 1500

// ── LVGL buffers (PSRAM) ──────────────────────────────────────────────────────
static lv_disp_draw_buf_t draw_buf;
static lv_color_t        *buf1;
static lv_color_t        *buf2;

// ── idle screen ───────────────────────────────────────────────────────────────
static lv_obj_t *idle_scr;

// Loads the Start/IDLE screen -- the device's resting state, waiting for a badge scan.
void screen_idle_load() {
    header_set_visible(true);
    header_set_current_user("");
    header_set_title("START");

    // Explicit control scheme, 2026-08-26 — matches the transaction screen's legend
    // convention (see build_idle_screen()'s footer). ENTER opens screen_admin_login_push()
    // — Admin Menu access is now a deliberate button+scan combo, not an automatic
    // consequence of a badge happening to be an admin's (see on_scan() below and
    // screen_admin_login.h for the reasoning). BACK calls screen_screensaver_push()
    // directly — the exact same function the real idle-timeout uses (idle_timer.cpp), so
    // this is a manual "kill the scanner light now" shortcut, not a separate code path —
    // whenever GM65 scan-mode logic gets wired into screen_screensaver_push()/cb_wake(),
    // it automatically covers both the timeout and this manual trigger at once.
    ButtonHandlers h;
    h.left  = screen_extras_push;       // "Extras" -- novelty/non-POS entries, see screen_extras.h
    h.right = screen_browse_push;       // scroll and/or scan-for-price, same screen now
    h.enter = screen_admin_login_push;
    h.back  = screen_screensaver_push;
    h.wantsScanner = true;  // the whole point of IDLE -- waiting for a badge scan
    buttons_set_handlers(h);
    idle_timer_arm();
    session_timer_disarm();  // nothing logged in at IDLE -- nothing to auto-log-out of

    lv_scr_load(idle_scr);
}

// ── LVGL callbacks ────────────────────────────────────────────────────────────
// LVGL's display flush callback -- pushes one rendered area out to the physical panel.
static void lv_flush(lv_disp_drv_t *drv, const lv_area_t *area, lv_color_t *color_p) {
    uint32_t w = area->x2 - area->x1 + 1;
    uint32_t h = area->y2 - area->y1 + 1;
    tft.startWrite();
    tft.setAddrWindow(area->x1, area->y1, w, h);
    tft.pushColors((uint16_t *)color_p, w * h, true);
    tft.endWrite();
    lv_disp_flush_ready(drv);
}

// ── init helpers ──────────────────────────────────────────────────────────────
// Initializes LVGL: PSRAM draw buffers and the display driver.
static void lvgl_init() {
    lv_init();
    buf1 = (lv_color_t *)heap_caps_malloc(SCREEN_W * 80 * sizeof(lv_color_t),
                                           MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    buf2 = (lv_color_t *)heap_caps_malloc(SCREEN_W * 80 * sizeof(lv_color_t),
                                           MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    lv_disp_draw_buf_init(&draw_buf, buf1, buf2, SCREEN_W * 80);

    static lv_disp_drv_t disp_drv;
    lv_disp_drv_init(&disp_drv);
    disp_drv.hor_res  = SCREEN_W;
    disp_drv.ver_res  = SCREEN_H;
    disp_drv.flush_cb = lv_flush;
    disp_drv.draw_buf = &draw_buf;
    lv_disp_drv_register(&disp_drv);
}

// Builds the Start screen's static content (label + legend) once, at boot.
static void build_idle_screen() {
    idle_scr = lv_scr_act();
    lv_obj_set_style_bg_color(idle_scr, lv_color_hex(C_BG), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(idle_scr, LV_OPA_COVER, LV_PART_MAIN);

    lv_obj_t *label = lv_label_create(idle_scr);
    lv_label_set_text(label, "Scan Badge\nTo Start");
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(label, 280);
    lv_obj_set_style_text_color(label, lv_color_hex(C_CYAN), LV_PART_MAIN);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_32, LV_PART_MAIN);
    lv_obj_set_style_text_align(label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
    lv_obj_align(label, LV_ALIGN_CENTER, 0, HDR_H / 2);

    // Explicit two-line legend, same convention as the transaction screen — every active
    // button spelled out rather than left to spatial/color intuition (see
    // feedback-ux-explicit-legends in project memory).
    lv_obj_t *legend = ui_legend(idle_scr);
    lv_obj_set_width(legend, SCREEN_W - 40);
    lv_obj_align(legend, LV_ALIGN_BOTTOM_MID, 0, -16);

    char left_arrow[24], right_arrow[24];
    snprintf(left_arrow, sizeof(left_arrow), "%s Extras", LV_SYMBOL_LEFT);
    snprintf(right_arrow, sizeof(right_arrow), "Browse/Price %s", LV_SYMBOL_RIGHT);
    ui_legend_row(legend, left_arrow, lv_color_hex(C_YELLOW), right_arrow, lv_color_hex(C_YELLOW));
    ui_legend_row(legend, "Admin Login", lv_color_hex(C_GREEN), "Screen Saver", lv_color_hex(C_RED));
}

// ── badge scan routing ────────────────────────────────────────────────────────
// Routes one scanned badge to whichever screen currently wants it (each screen's own
// *_on_scan() gets first refusal), falling back to the default "known user -> POS /
// unknown -> turned away" behavior if nothing claims it.
static void on_scan(const char *badge_id) {
    if (screen_setup_wizard_on_scan(badge_id)) return;  // first-boot/recovery wizard, if active
    if (screen_payment_edit_on_scan(badge_id)) return;  // Payment Info: owner scanning their own payment QR
    if (screen_enroll_on_scan(badge_id)) return;
    if (screen_pos_on_scan(badge_id)) return;  // TRANSACTION screen active — treat as an item UPC, not a badge
    if (screen_restock_on_scan(badge_id)) return;
    if (screen_add_item_on_scan(badge_id)) return;
    if (screen_item_edit_on_scan(badge_id)) return;  // viewing an item — link another UPC to it
    if (screen_add_user_on_scan(badge_id)) return;   // admin's "Add User" mode armed — this scan is the new person's badge, not a login attempt
    if (screen_browse_on_scan(badge_id)) return;     // Browse/Price screen active -- show that item's price
    if (screen_admin_login_on_scan(badge_id)) return; // Start screen's Admin Login armed
    if (screen_extras_on_scan(badge_id)) return;      // Extras' badge gate armed

    const User *u = users_find_by_badge(badge_id);
    if (u) {
        if (!u->active) {
            Serial.printf("[SCAN] Inactive user %d: %s %s — turned away\n", u->id, u->first_name, u->last_name);
            char msg[80];
            snprintf(msg, sizeof(msg), "Sorry %s,\nplease see the cart\nowner to continue.", u->first_name);
            screen_blocked_push(msg);
            return;
        }
        // 2026-08-26 — a plain scan no longer routes admins to the Admin Menu. That's now
        // a deliberate two-step action (screen_admin_login_push(), Start screen's Green
        // button, above) — a real fix, not just a preference: before this, an admin could
        // NEVER reach their own transaction via a plain badge scan at all, since this
        // branch always intercepted first. Now every known active user, admin or not,
        // just starts their own transaction on a plain scan.
        Serial.printf("[SCAN] Known user %d: %s %s\n", u->id, u->first_name, u->last_name);
        // TODO: screen_confirm_user_push(u->id, u->first_name) — for now go straight to POS
        header_set_current_user(u->first_name);
        screen_pos_push(u->id);
    } else {
        // 2026-08-25: used to self-enroll here (screen_enroll_push(badge_id)) — removed per
        // the owner's explicit "no guest checkout, all users manually enrolled by an admin"
        // call. See Add User (Admin Menu) for the replacement admin-gated enrollment path.
        // 2026-09-29: brought back behind an admin toggle (Admin -> Users -> Auto Enroll,
        // default OFF) at the owner's request. Same name wheel + re-scan-to-confirm as Add
        // User, so the badge number is still verified by a second scan before saving.
        if (users_auto_enroll_enabled()) {
            Serial.printf("[SCAN] Unknown badge: %s — auto-enroll\n", badge_id);
            screen_enroll_push_self(badge_id);
            return;
        }
        Serial.printf("[SCAN] Unknown badge: %s — not enrolled\n", badge_id);
        screen_blocked_push("Badge not recognized.\n\nPlease see an admin to\nget enrolled.");
    }
}

// ── Arduino ───────────────────────────────────────────────────────────────────
// Self-healing boot-time DB setup, 2026-09-14 — pulled out of setup() so screen_sd_error.cpp's
// Retry button can re-run exactly this on demand, not just at boot. If the primary DB won't
// open, or fails the deep check (db_sanity_check() reads every row and index, see db.h),
// restores the newest backup copy that passes the same check. Only attempts the restore once
// per call, no retry loop -- if no copy is usable, returns false so the caller can decide what that means (setup()
// lands on screen_sd_error_push() instead of the normal boot flow; a Retry press just stays
// on that screen with a refreshed diagnosis).
bool boot_try_init_db() {
    char db_note[32] = "ok";  // this boot's "db=" entry in the boot log
    if (!db_init() || !db_sanity_check()) {
        Serial.println("[DB] primary DB missing or failed the deep check -- attempting restore from backup");
        db_close();
        int slot = db_find_good_backup(false);
        if (slot >= 0 && db_restore_backup_slot(slot) && db_init() && db_sanity_check()) {
            Serial.println("[DB] restored from backup and reopened successfully");
            system_alerts_note_restored_from_backup();
            snprintf(db_note, sizeof(db_note), "restored_slot%d", slot);
        } else {
            Serial.println("[FATAL] DB unavailable even after a backup restore attempt");
            system_alerts_refresh();
            boot_log_note("db", "FAILED");
            return false;
        }
    }

    // A missing pos.db opens as a brand-new empty DB, which passes the sanity check above --
    // and the every-boot backup below would then copy that empty DB over the real backup.
    // 2026-10-02: if the live DB has no admin but a healthy backup does, the live one is almost
    // certainly a lost/replaced file, not a real fresh start -- restore before anything
    // overwrites the backups. db_find_good_backup() only reads, so a genuinely blank card
    // (no backups, or none with an admin) falls through to the setup wizard as before.
    int admin_slot = users_has_admin() ? -1 : db_find_good_backup(true);
    if (admin_slot >= 0) {
        Serial.println("[DB] live DB has no admin but a backup does -- restoring from backup");
        db_close();
        if (db_restore_backup_slot(admin_slot) && db_init() && db_sanity_check()) {
            Serial.println("[DB] restored from backup and reopened successfully");
            system_alerts_note_restored_from_backup();
            snprintf(db_note, sizeof(db_note), "no_admin_restored_slot%d", admin_slot);
        } else {
            Serial.println("[FATAL] DB unavailable after the no-admin backup restore");
            system_alerts_refresh();
            boot_log_note("db", "FAILED");
            return false;
        }
    }
    boot_log_note("db", "%s", db_note);
    boot_check_slide_free();

    // Leftover scratch files from a power cut mid-backup/restore/report -- see db.h.
    int cleaned = sd_cleanup_temp_files();
    if (cleaned > 0) boot_log_note("temp_files_removed", "%d", cleaned);

    // Data consistency, 2026-10-02 -- report-only, never changes anything (see db.h).
    {
        char data_note[160];
        if (db_consistency_check(data_note, sizeof(data_note)) > 0) {
            system_alerts_add_boot_issue("DATA CHECK FOUND PROBLEMS - SEE BOOT LOG");
        }
        boot_log_note("data", "%s", data_note);
    }

    // SD-layer check, independent of the DB-specific one above -- a card that's gone
    // write-protected or is failing can leave db_init()/db_sanity_check() looking fine
    // (both only ever read) while writes silently don't happen. Logged either way, not
    // gated on DB status, since it's worth knowing regardless.
    // Timed for the boot log: a card that's wearing out tends to get slower before it fails,
    // so a write time creeping up across boot_log.csv is an early warning (SD cards report
    // no health data of their own).
    uint32_t sd_t0 = millis();
    bool sd_write_ok = sd_write_read_test();
    uint32_t sd_ms = millis() - sd_t0;
    Serial.printf("[SD] write/read test: %s (%lums)\n", sd_write_ok ? "OK" : "FAILED", (unsigned long)sd_ms);
    system_alerts_set_sd_write_result(sd_write_ok);
    boot_log_note("sd_write", "%s", sd_write_ok ? "ok" : "FAILED");
    boot_log_note("sd_write_ms", "%lu", (unsigned long)sd_ms);
    boot_log_note("sd_used_kb", "%llu", SD.usedBytes() / 1024ULL);
    boot_log_note("sd_total_mb", "%llu", SD.totalBytes() / (1024ULL * 1024ULL));

    uint32_t bk_t0 = millis();
    bool backup_ok = db_backup_now();  // verified copy every boot, rotating the 5 slots -- see db.h
    boot_log_note("backup", "%s", backup_ok ? "ok" : "FAILED");
    boot_log_note("backup_ms", "%lu", (unsigned long)(millis() - bk_t0));
    system_alerts_refresh();  // picks up SD/DB status computed above, for the Admin Menu banner
    return true;
}

// Arduino entry point -- brings up the hardware, mounts the DB, and lands on whichever
// boot screen fits the DB's state (normal splash / setup wizard / hard error).
void setup() {
    Serial.begin(115200);
    delay(500);

    tft.init();
    tft.setRotation(0);
    tft.fillScreen(TFT_BLACK);
    backlight_init();

    lvgl_init();
    header_init();
    buttons_init();
    build_idle_screen();  // must run before any other screen loads -- it adopts lv_scr_act()

    // 2026-10-02: splash goes up FIRST and stays up through the whole boot (DB deep check,
    // any restore, backup rotation, GM65 config), then holds SPLASH_BONUS_MS more once boot
    // is done -- see screen_splash_release() below. lv_refr_now() paints it immediately,
    // since loop() (and with it lv_timer_handler()) doesn't run until setup() returns.
    screen_splash_hold();
    lv_refr_now(nullptr);

    bool dbOk = boot_try_init_db();

    idle_timer_load_from_config();     // picks up a saved screensaver timeout, defaults to 3 min otherwise
    screensaver_dim_load_from_config(); // picks up a saved screensaver dim level, defaults to 30% otherwise
    backlight_normal_load_from_config(); // picks up a saved normal brightness, defaults to 100% otherwise
    session_timer_load_from_config();  // picks up a saved auto-logout timeout, defaults to 5 min otherwise
    rtc_init();  // DS3231 -- safe no-op if not wired yet, see rtc.h

    // Clock health, 2026-10-02 -- every sale is timestamped, so a clock that lost its
    // battery, shows an impossible year, or runs behind the newest sale gets flagged
    // (boot log + Admin Menu alert) instead of quietly mis-dating reports.
    clock_health_check();
    {
        char clock_note[64];
        clock_health_summary(clock_note, sizeof(clock_note));
        boot_log_note("clock", "%s", clock_note);
    }
    system_alerts_refresh();  // boot_try_init_db() refreshed before the RTC was up
    webserver_init();  // routes only, radio stays off -- no web login, see webserver.cpp's header

    scanner.begin(9600, SERIAL_8N1, 16, 15);  // ESP RX=16 (← GM65 TX), ESP TX=15 (→ GM65 RX)

    // Force the known-good config every boot (see comment at gm65_write_reg() above).
    // Free real estate time-wise — the splash screen is already up for the whole boot
    // regardless, so this rides along with a wait the user experiences anyway. Small
    // delays between writes, not fired back-to-back — matches the pattern already proven
    // safe in screen_gm65_test.cpp's act_setup_defaults(). The ACK replies themselves
    // aren't drained here at all anymore: screen_splash_is_active() (checked in loop(),
    // same pattern as the screensaver) ignores any scanner traffic for as long as splash
    // is actually on screen, so there's no need to guess a "long enough" blocking delay —
    // it's covered for the splash's whole real duration, however long that ends up being.
    gm65_write_reg(0x00, 0x00, 0x57);  // Induction + Light Normal + Aim Normal + Buzzer on + LED off
    delay(30);
    gm65_write_reg(0x00, 0x07, 0x00);  // sleep-on-idle off
    delay(30);
    gm65_write_reg(0x00, 0x0A, 0x64);  // buzzer passive mode @ 2000Hz — 0x00 (Active) produces
                                        // just a click on this unit's actual buzzer hardware,
                                        // confirmed via a real register readback, not a guess
    delay(30);

    // 2026-09-29 — actively drain those three ACKs here, same drain-til-quiet pattern as
    // buttons.cpp's drain_scanner_ack(). Before this, the setup wizard relied on loop()'s
    // blanket "ignore scans while this screen is up" guard to dodge them -- which also
    // ignored every REAL badge scan, so a blank-card setup could never get past its first
    // prompt (caught on real hardware). Splash/SD-error keep their loop() guards (neither
    // wants scans anyway); the wizard no longer needs one.
    bool scanner_acked = false;
    {
        uint32_t start = millis(), last_rx = 0;
        bool &saw_any = scanner_acked;
        while (millis() - start < 500) {        // fault-guard if the module never answers
            if (scanner.available()) {
                while (scanner.available()) scanner.read();
                last_rx = millis();
                saw_any = true;
            } else if (saw_any && millis() - last_rx >= 40) {
                break;                          // replies received, bus quiet since
            }
            delay(1);
        }
    }
    boot_check_scanner(scanner_acked);

    // This device does nothing useful without a working DB (no items, no users, no
    // checkouts) -- rather than let a regular user wander into a Start screen that can't
    // actually do anything, land on a dedicated blocking error screen instead. Its own
    // Retry button re-runs boot_try_init_db() and falls through to the normal flow the
    // moment it succeeds, no reboot needed.
    //
    // A DB that opens fine but has no admin row is a related dead end, not a healthy boot
    // either -- Admin Login (and everything behind it, including the normal Add User flow)
    // requires an existing admin badge to scan, so a blank/fresh SD card (or one that's
    // lost every admin row some other way) can never reach Admin Login again on its own.
    // screen_setup_wizard_push() is the escape hatch, 2026-09-14 -- replaces the old
    // seed_users.csv SD bulk-import as this project's answer to "how do real people get
    // onto a fresh device" for the admin-bootstrap case specifically.
    if (!dbOk) {
        screen_sd_error_push();
    } else if (!users_has_admin()) {
        screen_setup_wizard_push();
    } else {
        screen_splash_release(SPLASH_BONUS_MS);  // splash is already up -- hold a little, then IDLE
    }

    // Boot log, 2026-10-02 -- written last, so it has every check's result and the RTC-synced
    // time. An unexpected restart (brownout/crash/watchdog) also raises an Admin Menu alert.
    if (boot_log_unexpected_restart()) system_alerts_note_unexpected_restart(boot_log_reset_reason());
    // Stuck-button check, last thing before logging -- by now a button held at power-on
    // has had the whole boot to be let go of, so anything still down is really stuck.
    {
        char stuck[48];
        if (buttons_check_stuck(stuck, sizeof(stuck)) > 0) {
            boot_log_note("stuck_buttons", "%s", stuck);
            system_alerts_add_boot_issue("BUTTON STUCK DOWN AT BOOT");
        }
    }
    boot_log_note("free_heap_kb", "%u", (unsigned)(ESP.getFreeHeap() / 1024));
    boot_log_note("boot_ms", "%lu", (unsigned long)millis());
    boot_log_write();

    // Reconciles the scanner's real state (just forced to Induction/sensing, above)
    // against whatever screen buttons_set_handlers() was called for earlier in setup()
    // (splash, the setup wizard, or the SD/DB error screen, depending on boot outcome)
    // -- those calls happened before scanner.begin() even ran, so they couldn't act on
    // it yet. See buttons.h/buttons.cpp for the per-screen on/off system this feeds into.
    buttons_scanner_ready();
}

// Arduino main loop -- polls buttons, ticks LVGL/idle/session timers, and reads any
// pending scanner data, routing it to on_scan() unless something's actively armed to
// intercept it (Scanner/GM65 Settings) or the active screen doesn't want scans at all.
void loop() {
    buttons_poll();  // sample input first — don't let a slow render delay picking up a press
    lv_timer_handler();
    idle_timer_check();
    session_timer_check();
    // The AP only belongs on the Web Portal screen. Its Back turns it off, but any other
    // exit (auto-logout especially) used to leave the radio -- and the portal -- running.
    if (webserver_ap_running() && !screen_webportal_is_active()) webserver_stop_ap();

    if (scanner.available()) {
        String code = scanner.readStringUntil('\n');

        if (screen_gm65_test_capture(code.c_str(), code.length()) ||
            screen_gm65_settings_capture(code.c_str(), code.length())) {
            // Scanner or GM65 Settings screen is active and this looked like a command
            // reply/ACK, not a real badge/UPC scan — consumed above, don't fall through.
        } else {
            code.trim();
            if (code.length() > 0) {
                // Screensaver deliberately doesn't wake on a scan (only button presses) —
                // see screen_screensaver_is_active(). Splash gets the same treatment so the
                // boot-time GM65 config writes' ACK replies (setup(), above) don't get
                // misrouted here as a bogus scan. The SD/DB error screen needs the identical
                // guard for the identical reason — it runs instead of splash whenever the DB
                // is broken, but the GM65 writes (and their ACK replies) happen unconditionally
                // right after either one loads, so without this a stray ACK got read as an
                // "unknown badge," which then routed through screen_blocked -> screen_idle_load()
                // and escaped the error screen entirely (caught on real hardware 2026-09-14).
                // The setup wizard USED to be guarded here too (2026-09-14), but that also
                // swallowed its real badge scans -- removed 2026-09-29; setup() now drains
                // the boot ACKs synchronously instead, see there.
                // Still drain the UART either way so bytes don't pile up.
                if (screen_screensaver_is_active() || screen_splash_is_active() ||
                    screen_sd_error_is_active()) {
                    Serial.printf("SCAN: [%s] — ignored, splash/screensaver/error screen active\n", code.c_str());
                } else {
                    Serial.printf("SCAN: [%s]\n", code.c_str());
                    on_scan(code.c_str());
                }
            }
        }
    }

    delay(1);
}
